<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputMonthUsed</name>
   <tag></tag>
   <elementGuidId>4e9e6d85-69fc-4cf4-bfc1-8d45694f7834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meter_month_used</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='meter_month_used']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb2c4efb-dca8-4f98-8f55-690d033551ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9ed22797-edc4-4b7a-ba53-cfa2a5579b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>month</value>
      <webElementGuid>5fe5cb6d-f15f-4c9d-b4d7-1e4b1dc0a84b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>meter[month_used]</value>
      <webElementGuid>c0ad3e9f-b74f-4e17-b966-5afb84beb97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meter_month_used</value>
      <webElementGuid>3c84f1c9-0fc1-4a6e-b127-63712b59277d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meter_month_used&quot;)</value>
      <webElementGuid>bd0136b6-cbc1-4eda-8c56-5c4e6ef915d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='meter_month_used']</value>
      <webElementGuid>4f2f56f0-280d-45a0-8c71-455528a4f99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_meter']/div/div/input</value>
      <webElementGuid>a69924c2-d880-4aa3-b822-e07ef89ccc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>57cdbffb-4fd3-40fe-a7c5-17defe0c081e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'month' and @name = 'meter[month_used]' and @id = 'meter_month_used']</value>
      <webElementGuid>59d85685-d4f7-43f6-9033-49fba98948de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
