<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputWaterIndex</name>
   <tag></tag>
   <elementGuidId>1867282a-916c-4dd4-8d33-835690afe21d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meter_water_index</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='meter_water_index']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1cec0284-11e3-427d-879c-39c7daaaea37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ef5297b7-5fbd-4508-9af8-b35826359cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d31def0f-a08e-4fb1-a9a6-1d16612f57ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e6f1d972-0394-4577-8ba7-ff4b5041c69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>meter[water_index]</value>
      <webElementGuid>8182c4d8-8ddf-4f56-ac34-173fda66db57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meter_water_index</value>
      <webElementGuid>35108f5a-d6b0-4de4-8c32-263ae16c480a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meter_water_index&quot;)</value>
      <webElementGuid>53233179-c3d8-4b9c-b10e-cbf9b130b055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='meter_water_index']</value>
      <webElementGuid>09eb2239-ea2c-4869-8d18-34ec864ffe5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_meter']/div[3]/div/input</value>
      <webElementGuid>ce670ad9-6d30-475a-8d59-26cf40984825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2626d1e5-469a-4ecb-ba7d-bbcbc6b00814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'meter[water_index]' and @id = 'meter_water_index']</value>
      <webElementGuid>0801e6a7-5b23-456d-8eca-13034759050e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
