<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputAmountOfMembers</name>
   <tag></tag>
   <elementGuidId>9266b9cf-f8a0-4113-acbc-4e46ab342be4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meter_amount_of_members</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='meter_amount_of_members']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ac3fbef-0de1-45bd-9dd1-a351c0a327e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fa5ad48c-0e67-42b9-b8b9-51c6dd480287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d18b596-42e8-4ae7-9024-4a63dda6cf0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>700d5986-5e17-48c3-9961-47bc011d7fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>meter[amount_of_members]</value>
      <webElementGuid>3cecb6af-40cf-4547-8123-eccc7082d59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meter_amount_of_members</value>
      <webElementGuid>3aaa708a-6249-403e-8743-a5a0b4649c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meter_amount_of_members&quot;)</value>
      <webElementGuid>fc73a764-d70f-4359-9844-389f12fd805b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='meter_amount_of_members']</value>
      <webElementGuid>b23f8b82-8987-49a3-8a01-c6b3b890857a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_meter']/div[4]/div/input</value>
      <webElementGuid>495ccf70-5f15-4798-b569-704a1239e995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>e7356982-1675-44e7-be07-ef31d569a596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'meter[amount_of_members]' and @id = 'meter_amount_of_members']</value>
      <webElementGuid>ea5ae8de-4eb6-458a-9efb-853118d096c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
