<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputElectricityIndex</name>
   <tag></tag>
   <elementGuidId>a902e5a5-46fe-4517-a6a7-12dd6b364df8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meter_electricity_index</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='meter_electricity_index']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0691cfa-199b-4d12-a485-99a545ca89be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>325f0977-0736-4e81-85a1-446c36ad501d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd6d7cde-c5ce-4ac2-8a0c-0551c0d2b725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>49ee0053-b375-4f76-85da-3fe0cdbfd9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>meter[electricity_index]</value>
      <webElementGuid>e8c885b9-a4a4-4065-8f05-ddb4cbd15660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meter_electricity_index</value>
      <webElementGuid>31fbdbfd-67bb-42f3-8dd1-23893a6f876d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meter_electricity_index&quot;)</value>
      <webElementGuid>dc03e185-6fee-4279-a5cb-7c499e1368e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='meter_electricity_index']</value>
      <webElementGuid>0b56ca90-7240-4791-b0e6-bd84d909c34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='new_meter']/div[2]/div/input</value>
      <webElementGuid>41c809b3-ae2d-47ce-8fb2-27d7b215e2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>58ba4117-acc6-4087-bfeb-5a96969ae64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'meter[electricity_index]' and @id = 'meter_electricity_index']</value>
      <webElementGuid>6db320ce-a043-4bb8-a8f1-88da811208ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
